[package]
name = "hello_move_lab"
version = "0.0.1"
edition = "2024.alpha"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework-latest" }

[addresses]
hello_lab = "0x0"
